/**
 * Fact sheet microcopy schema (W2.5). The strings live in ./copy.ts (EN + ID).
 * Strings may contain {placeholders}; a string uses the same placeholders in
 * every language. Statements, reasons, and quotes are never copy: they come
 * from data/status verbatim.
 */
import type { FlagName } from "../flags/types";

export const LANGS = ["en", "id"] as const;
export type Lang = (typeof LANGS)[number];

export type AssetType = "fund" | "bond" | "commodity" | "yield-bearing";

export type FactSheetCopy = {
  /** The language's own name for the switcher ("English", "Bahasa Indonesia"). */
  languageName: string;
  meta: {
    /** Browser title. {code}, {issuer_org} */
    title: string;
    /** Meta description. {code}, {issuer_org} */
    description: string;
    indexTitle: string;
    indexDescription: string;
  };
  nav: {
    allAssets: string;
    /** Label of the language switcher. */
    language: string;
  };
  header: {
    /** Small label above the asset code. */
    eyebrow: string;
    issuer: string;
    issuerAccount: string;
    assetType: string;
    /** {date} = YYYY-MM-DD */
    statusAsOf: string;
    /** {datetime} = ISO time, UTC */
    computedAt: string;
  };
  assetTypes: Record<AssetType, string>;
  /**
   * One sentence under the status badge. The badge shows the feed value
   * itself (OK, WARNING, CRITICAL); `unpublished` is the badge text when status is null.
   * {raised}, {clear}, {not_evaluated} = counts.
   */
  status: {
    OK: string;
    WARNING: string;
    CRITICAL: string;
    unpublishedBadge: string;
    unpublished: string;
  };
  counts: {
    /** {n} */
    raised: string;
    clear: string;
    notEvaluated: string;
  };
  sections: {
    raisedTitle: string;
    raisedIntro: string;
    raisedEmpty: string;
    clearTitle: string;
    clearIntro: string;
    notEvaluatedTitle: string;
    notEvaluatedIntro: string;
    methodTitle: string;
    /** Date line under each flag. {date} */
    asOf: string;
  };
  /**
   * Shown once above the flag lists: statements and reasons are generated by
   * code and recorded in English, shown word for word.
   */
  computedTextNote: string;
  flags: Record<FlagName, {
    /** Short human name, e.g. "Supply vs. documents". */
    name: string;
    /** One sentence: what the check compares. Neutral; no promise of safety. */
    checks: string;
  }>;
  /** Severity labels stay the feed values; these explain review state. */
  review: {
    /** CRITICAL computed, counted as WARNING until an operator confirms it. */
    pending: string;
    confirmed: string;
    /** An operator did not confirm it; counted as WARNING. */
    rejected: string;
  };
  evidence: {
    title: string;
    source: string;
    quote: string;
    location: string;
    snapshot: string;
    /** {date} */
    chainCheck: string;
    /** {date}, {check} = examination check id */
    examination: string;
    documentSnapshot: string;
    horizonLink: string;
    explorerLink: string;
    /** Where an evidence item has no public link. */
    noPublicLink: string;
  };
  method: {
    /** 4–6 short steps: chain read, documents, quote verification, deterministic flags, what the LLM does and doesn't do. */
    steps: string[];
    inputsTitle: string;
    checks: string;
    previousChecks: string;
    examinations: string;
    rulesVersion: string;
    feedTitle: string;
    bitmask: string;
    evidenceHash: string;
    /** Short note: feed status (planned, not live) and what the bitmask and evidence hash are. */
    feedNote: string;
  };
  disclaimer: string;
  index: {
    title: string;
    intro: string;
    asset: string;
    issuer: string;
    type: string;
    status: string;
    flagsRaised: string;
  };
};
